### ISSUE TITLE
Improve Editor Plugin GUI

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#134]
**This issue is WIP. Details will be added after an initial analysis phase.**

### Benefit description

The first contributions came when the plugin was not very documented, and they introduced a number of inconsistencies in the GUI.

Also, some of them came from experience with other engines, and they took a form that catered more to them than Godot.

We must improve the consistency of the plugin interface: inspectors, toolbar, popups, etc.

### Solution description

**WIP - More will be added**

Here is a list of tasks to be performed in the scope of this issue:

* [x] Walkable Areas polygon edit button should be moved from the inspector to the toolbar
* [x] Refactor and improve the editing button canvas menu:
    * [x] Clicking a selected gizmo (like InteractionPolygon) should toggle back to the related PopochiuClickable node
    * [x] The present Baseline and WalkToPoint buttons should not select node helpers, but toggle the visibility of the new gizmos instead (split out of #232 )
    * [x] General refactor of the code, that can be simplified
* [x] ~~Gizmos may be designed on the viewport instead of resorting to elements in engine objects.~~ (Addressed in #232 )
* [x] #67 may be in scope for this issue
* [x] ~~Consider changing "DialogPos" marker2d to a property of the character, with its own gizmo, to keep things consistent~~ (split in #232)
* [x] Fix the bug of popup windows on Linux being too large on the vertical axis at first load
* [x] Make sure aseprite command defaults to an empty string in the distributed plugin to avoid errors
* [x] When you select an element in a room scene while editing another element's polygon, the polygon don't get hidden, but it should.

### Exclusions

TBD

### Implications

TBD

**Comment by stickgrinder** [comment]
Closed by last commit by @drbbgh
