### ISSUE TITLE
Create a gizmo for polygon editing

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#243]
### Benefit description

Currently, all the Popochiu Objects that depend on a polygon (be it an `InteractionPolygon2D` or a `NavigationRegion2D`), allow the editing of the polygon shape through a button that selects the inner node "behind the scene".

This works, but it is susceptible to a lot of problems. For example:

* It is difficult to manage the selection code and it requires a bit of trickery to jump back and forth between the parent node and the polygon inside it
* If a node has more polygons (to represent "holes", or composite colliders - see #10 ), a single button to edit them all simply doesn't work
* The user has to press a button to edit the polygon explicitly, or even just to see it on the scene, making the interaction annoying.

We need a better solution

### Solution description

As silly as it sounds, we need to implement a new 2D gizmo, using the same strategy we used in #232.

By painting on the viewport we may create a polygon gizmo tool that connects to one or multiple elements inside its node, and sports a tailored interaction.

Most of its behaviors will mimic normal polygon editing, but it may be switched from read-only (see-only) to editing mode, or change more polygons at once. Or even allow the creation of "holes" that are very useful in walkable areas.

### Exclusions

- Cutting holes in a polygon may have to be postponed to a second stage.
- No toolbar for the creation of polygons will be implemented at the moment.

### Implications

This gizmo can be based on GD Extensions, as @drbbgh suggested, but this may be unfeasible if we want to represent more polygons with a single gizmo. We have to check.

### Tasks list

* [ ] Evaluate creating specialized classes in a tree, like
    ```mermaid
        classDiagram
            Gizmo2D <|-- Gizmo2DPos
            Gizmo2D <|-- Gizmo2DAxis
            Gizmo2D <|-- Gizmo2DPoly

            class Gizmo2DPos{
                <<Point in 2D space>>
            }
            class Gizmo2DAxis{
                <<Horizontal or vertical position>>
            }
            class Gizmo2DPoly{
                <<Irregular, composite polygon>>
            }
    ```
* [x] Create a `Gizmo2DPoly` class that holds an array of arrays of vertices. Each array of vertices is a copy of a `CollisionPolygon2D.polygon` or a `NavigationRegion2d.navigation_polygon.get_outline()`. Supporting more polygons will allow _clickables_ to have more than one collision polygon, supporting complex cases.
* [x] The class will make use of a `Polygon2D` instance for each array of vertices, plus a `Gizmo2DPos` (or `Gizmo2D` of type `GIZMO_POS`) for each vertice. These elements will help draw the polygon on the screen. Of course, each vertex gizmo must hold the set of indexes that identifies it in the arrays.
* [x] The array of array of vertices must always be populated from the bound properties of the target nodes, which are the ultimate source of truth about the state of the polygons.
* [x] `Gizmo2DPos`-enabled vertices can be moved around, updating the corresponding vertice in the array of arrays. Pressing ESC, the value is read back from the target nodes. Releasing the mouse button, the value is saved and persisted to the target nodes.
* [x] New vertices must be added by clicking on a connecting line, with a 5-pixel (screen pixels) tolerance (_I have no idea how to achieve this with Polygon2D, atm_) (note: this will update the indexes of all gizmos, so this is one of the actions that should trigger a complete repaint)
* [x] Vertices must be removed by left-clicking on them (same as above about the repaint).

### Additional tasks to address

* [ ] #498
* [x] Toolbar needs some visual adjustment after upgrade to Godot 4.6 (which has a new theme)
* [x] Implement the options to always show polygons. Maybe add the option to the Popochiu toolbar with a set of checkboxes in a dropdown?
