### ISSUE TITLE
Checklist: 2.0 Stable release

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#282]
### Description

Things to do at the release of 2.0 Stable

### Todo

* [x] Fix broken links in "Getting Started" docs section (@stickgrinder)
* [x] Test migrations for the last time (@mapedorr)
* [x] Review new README files (@mapedorr)
* [x] Prepare markdown file with release notes (@mapedorr)
* [x] Write release announcement (@stickgrinder) and review (@mapedorr)
* [x] Merge new icons and branding (@mapedorr)
* [x] Make sure the code reference is exported (@stickgrinder)
* [x] Publish new branded doc site to gh-pages (@stickgrinder)
* [x] Rebrand the Itch page (@stickgrinder)
    * [x] Colors and fonts (@stickgrinder)
    * [x] Description based on the new readme files (@stickgrinder)
    * [x] New cover image
* [x] Publish and tag the sample project (@stickgrinder)
