### ISSUE TITLE
Refactoring and code cleanup for Popochiu 2.0

### ISSUE THREAD

**Issue by mapedorr** [carenalgas/popochiu#43]
A list of tasks to work on in order to reach the Beta state of version 2 (the order doesn't matter).

- [x] Deletion of objects working (room, character, inventory item, dialog, prop, hotspot, walkable area, region).
- [x] #8 
- [x] #18 
- [x] Refactor the object creation popups: same as the previous one.
- [x] #22 
- [x] `PopochiuObjectRow` and `PopochiuAudioRow` refactoring (both are similar and have a lot of duplicate code).
- [x] Move the content of `types_helper` script, into PopochiuEditorHelper
- [x] Reduce complexity of **Popochiu.gd**. It takes care of a lot of things.
  - [x] Move room related functions to the **i_room.gd**.
  - [x] Move camera related functions to a script for the main camera.
  - [x] `_eval_string(text: String)` could be something handled by **i_character.gd**.

**Comment by mapedorr** [comment]
[This commit](https://github.com/carenalgas/popochiu/commit/030f3952f46fa8919d3f6431c45af88dc0e88927) make progress on refactoring `popochiu.gd`.

**Comment by mapedorr** [comment]
Thanks!

**Comment by mapedorr** [comment]
Closed with #236
