### ISSUE TITLE
Aseprite importers

### ISSUE THREAD

**Issue by stickgrinder** [carenalgas/popochiu#8]
This idea is heavily inspired by PowerQuest's importers, which is a key component of the framework's streamlined workflow.

Basically, when a new room or character are created, a new importer prefab is generated. This importer takes a properly organized Aseprite file as source and automatically creates animations for room props, character or inventory items.

## Aseprite file layout

The Aseprite file for a room will contain all the room props isolated on their own frames. Each prop will have its frame(s) tagged wiith the prop's name. Some props will be represented by a single frame, some other will have more than one frame.

The following example shows a quick and dirty scene with a `Background` prop, a `Trees` prop, a `Tent` prop and a `Rock` prop. All of them are static, represented by a single frame. The `Fire` prop instead is animated so its tag extends along four frames.

![immagine](https://user-images.githubusercontent.com/625436/188014204-b732d27d-5add-4ddf-ac08-60bd0b78233d.png)

Layers, although convenient, are not relevant to the file organization. The first frame contains the whole image but is not tagged. This frame is also there for convenience but will not be taken into consideration by the importer, lacking a named tag.

The props frames will have a transparent background, as shown in this animation:

![Popochiu Room Example](https://user-images.githubusercontent.com/625436/188015623-02973c8c-d811-4505-8f7a-aa927670f446.gif)

## Importer

Each specific room should ideally have an importer panel. This panel may be organiized as follows:

![importer-interface-mockup](https://user-images.githubusercontent.com/625436/188019083-1af081dc-fb00-4807-8f3b-b62f03bdf2f7.jpg)

1. Here you specify the source Aseprite file
2. This button scans the file for tags and their position/duration. Clicking it populates the subsequent list
3. Each tag found is shown with name (it will become the animation name), starting frame (for convenience) and the following actions:
  * Open the animation in Godot Animation Editor
  * Reload animation sprites and rebuild the animation
  * Toggle animation loop (not all animations are looping, this should ideally set/unset the animation flag without the need to open the animation in the editor, as well as showing if the animation is looping at a glance)
  * Additional dropdown menu for possible other actions (delete all frames+anim, rename, whatever)
4. This will bulk reimport all sprites, useful for massive operations like global recoloring, palette changes, repainting over progammer's art, etc
5. This will rebuild all animations, useful after re-scanning a file, if the animations changed number of frames

When the you click "import files", the importer script invokes Aseprite to export every tagged frame with a proper naming (`tag_NN.png`), placing every sprite in a `Sprites` subfolder in the Room/Character/Inventory directory.  
The import settings for those sprites should be defined at project level.

Building animations actually creates animations **even for single frames elements**. This is not actually necessary but it shouldn't hurt that much in terms of performance and will keep things tidy, no need to handle special cases or introduce fallback logic from animations, to single sprites.

This may seem a bit overkill, but it supports the evolutionary workflow from sketches, to programmer's art, to definitive artwork, where a single frame prop may end up animated during the process. In this case, reimporting a whole room once painted in Aseprite is just three clicks away.

### Sprites size

In this case, sprites are not trimmed and every prop sprite in the scene is basically an image large as the scene itself, with the majority of it's space filled with transparent pixels.

Again, this is not going to hurt: this way the props placing in the scene is automatic. Each single prop is actually in the same position and the scene will compose itself importing the sprites.

Baselines, walk-to points and look-at points will define the actual placement of the prop in the game world, but from a tachnical perspective they are in the same place. Programmatically moving a prop is still an option.

### Other objects

The example in this issue has been done for a Room, but characters may be treated the same. There is no difference, you tag the source file, scan it, import sprites and build animations. The looping/non looping toggle comes particularly handy here, since characters have both looping and non loopring animations usually.

Inventory may also benefit from such an importer, but each game will usually have one for the whole inventory so that a single Aseprite file can hold all the icons (even animated).

**Comment by stickgrinder** [comment]
Forgot to mention this Godot Plugin that's doing more or less the same: https://github.com/viniciusgerevini/godot-aseprite-wizard

I'm not sure if we can rely on this, considering it would be great to have a contextual import for each game entity (to keep sprites and anims in the right folder, as well as mapping the correct source file on each entity). We can still take inspiration for the user interface if it's better than my proposal.

**Comment by stickgrinder** [comment]
I took a look at https://github.com/viniciusgerevini/godot-aseprite-wizard and it already does a great job OOTB.
It works with AnimationPlayer objects, we are about to introduce to manage animations by default on Characters, Props, Cursors and Inventory Items and it does all the heavy lifting.

Also it's readily available for Godot 4.0 already (version 6).

Still I think we may fork it (MIT license, crediting the original author is mandatory) and change some of the behaviors it sports, notably:

- We may make it lighter ditching AnimatedSprite support, since we're not going to use it for animations.
- Its interface doesn't currently allow to inspect tags in source files, so you don't know what you are importing. An interface similar to the one depicted in this issue would better serve our needs and give access to animation management outside the AnimationPlayer windows, which is not for faint-hearted.
- I would try and understand if we may have different spritesheets for each animation. This would make easier and safer to get rid of unwanted animation and process (mostly REprocess) them in isolation. Importing performances are not wonderful...
- Somewhat important to me, this plugin automatically attaches to the Sprite or AnimatedSprite objects inspector. I would change this to make it available on the inspector of Popochiu game entities (Characters, Props, etc) so that the inner workings are hidden from the final user (so they doesn't have to learn useless info on internal objects structure and we are free to change stuff under the hood in the future, without breaking user experience or re-documenting everything)

I think this set of changes would make for the perfect solution.

**Comment by mapedorr** [comment]
I'll take a look to the plugin to get familiar with it, but what you're mentioning sounds good. In the future we should not rule out that some developers will prefer to use AnimatedSprite instead of AnimationPlayer, but to start with, and for flexibility, I agree that we focus on the second one.

**Comment by stickgrinder** [comment]
I think we should give one option that's "the Popochiu way". Every Godot-savvy (or unsavvy) dev who wants to break the tool to pieces, rearrange things as they sees fit and whatever, but in that case he should be knowing what to do (there can be dragons, you're on your own, etc)

Maybe, for those architectural choices that are less of a no-brainer, if we are unsure in the first place, documentation on how to safely take the other route may be a good addition.

What do you think?

**Comment by stickgrinder** [comment]
Leaving here some notes to myself after reading [this plugin](https://github.com/viniciusgerevini/godot-aseprite-wizard) code:

### Cleanup grocery list:

* [ ] We should "port" the desired functions into Popochiu plugin, with the following changes
  * [ ] Remove support to AnimatedSprites: we'll rely on AnimationPlayer + Sprite pairs (as for #18)
  * [ ] Remove single layer selector as well as exclusion regex pattern in inspector plugin: in a first iteration we'll import all layers, with an option to import only visible ones. In a further iteration we can add a proper list with selection checks.
  * [ ] In the AnimationPlayer support we'll remove support for Sprite3D and TextureRect, we'll only use sprites.
  * [ ] All plugins configuration will be moved to Popochiu config section, together with constants, helpers, etc.
  * [ ] We'll get rid of the generic Wizard function, found under "Project -> Tools" section, together with the History tab: generic importer won't be supported (if needed for a project one of the many available plugins can be installed for that).

### Additions and changes grocery list:

  * [ ] **IMPORTANT** We need to switch from a spritesheet to a one-file-per-frame mode because for props (mostly if handled as PQ does) we'll surely hit the infamous ["Big images" problem](https://github.com/viniciusgerevini/godot-aseprite-wizard) but the solution proposed by this plugin is excessively convoluted AND it imposes unwanted behaviors to the source Aseprite files.
* [ ] We'll scan the Aseprite file to read every tag before importing to populate an interface like the one shown in description.

All of this needs further investigation and it will take a while (a good while), but at least we have some code to rely upon to do the heavy lifting.

**Closing note**: this plugin is really good!

**Comment by stickgrinder** [comment]
OK, done a decent improvement!

### "Minor" cleanups

* [ ] Interface sucks, it's just a draft at the moment, I'll make it sexier once everything works
* [ ] Animations are added but not removed when you reimport eveything from scratch, I plan to add an option to keep the anims that are already there (useful for multi-source workflows)
* [ ] I want to add a button to reset all the settings, just in case
* [ ] When you rescan the file, only the defaults are applied at the moment. This is very inconvenient because if you just added an animation but wants all your loops settings to stay put, this is very annoying. I'm obviously planning to fix this.

### Major features (some may be moved to separate cards)

* [ ] Animations must be saved as external resources and loaded in the AnimationPlayer by default
* [ ] A button to delete an animation should be in the interface
* [ ] (to be split, maybe) Evaluate a function to reload the single Animation (this is in PQ but may make little sense for we are stuck with animations atlases)
* [ ] (to be split, for sure) One more plugin may provide a panel with an AnimationPlayer to programmatically load animation-resources in it for editing purposes, without moving to the actual PopochiuObject AnimationPlayer

**Comment by stickgrinder** [comment]
The bulk of this is done. I'm going to open a draft PR in the meantime.

The Major features will be ported to specific issues.
